### ISSUE TITLE
TERRA-64 ⁃ Expose service_name attribute from astra_private_link independent of an astra_database

### ISSUE THREAD

**Issue by muresan** [datastax/terraform-provider-astra#133]
## Feature request
We have a setup on GCP where there is a `networking` project which hosts the VPC and a `compute` project which hosts the compute resources and where "virtually" the DataStax resources will be created (basically a pipeline that creates resources in the `compute` project will also create datastax resources).. Specifically for GCP Private Service Connect there is a dependency that `astra_private_link_endpoint` depends on `astra_private_link` which depends on `astra_database` so a database needs to exist prior to any other resource.
Would it be possible to export the `service_name` resource from `astra_private_link` if they are static per GCP region so that we can create before and independent of an `astra_database` the `astra_private_link` and `private_link_enpoint` resources in the `networking` project and then just reuse them from the `astra_database` resource?

### Terraform Version
N/A

### Affected Resource(s)
* astra_private_link

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-64) by [Unito](https://www.unito.io)
┆friendlyId: TERRA-64
┆priority: Major

**Comment by emerkle826** [comment]
@muresan Thanks for the request.

It is currently not possible to create a Private Link in Astra without first creating an Astra DB. The `service_name` for a private link is also not known until the private link resource is created within Astra, so there is no way to export or predict it prior to creating the resource.

> and then just reuse them from the astra_database resource?

This is backwards in the way it works in Astra. A private link resource in Astra isn't independent of the DB, so there isn't a way to just create one, and then associate it with a DB. An Astra DB is independent of a private link resource, which is why the resource relationship is the way it is in the provider.

From your description, I believe you are wanting to create your GCP resources and manage them outside the lifecycle of some Datastax Astra resources. Unfortunately the way the resources are created, you have to have a DB before you can create a private link, and you need the service name from the private link to create some of the GCP resources you need for Private Service Connect to work. There is an example config that shows how the resources depend on each other [here](https://registry.terraform.io/providers/datastax/astra/latest/docs/resources/private_link_endpoint). The only thing missing from the example is the astra_database section. The example assumes the database is already created, but it could easily be changed to include the Database definition as well, and then the DB ID and Datacenter ID wouldn't have to be hard-coded in the example. But the resource relationships are the key to the answer here.

**Comment by muresan** [comment]
> @muresan Thanks for the request.
> 
> It is currently not possible to create a Private Link in Astra without first creating an Astra DB. The `service_name` for a private link is also not known until the private link resource is created within Astra, so there is no way to export or predict it prior to creating the resource.
> 
> > and then just reuse them from the astra_database resource?
> 
> This is backwards in the way it works in Astra. A private link resource in Astra isn't independent of the DB, so there isn't a way to just create one, and then associate it with a DB. An Astra DB is independent of a private link resource, which is why the resource relationship is the way it is in the provider.

Thank you for the reply.

Yes the need is to split networking related resources from services related resource in the case of a company with multiple teams with separate roles.
Ideally the PSC would have a longer lifecycle than a database and can be reused for multiple databases (like for example is the case with Elastic Cloud GCP PSC: https://www.elastic.co/guide/en/cloud/current/ec-traffic-filtering-psc.html which publish a list of per region target attachment URIs so you can provision the GCP PSC ahead of time) so that's why I asked hoping that there is an option.

In the case of one terraform file deploying all the resources this is not an issue but in the case of permissions split across multiple terraform modules/teams I encountered this and thought I should ask.

**Comment by emerkle826** [comment]
> Ideally the PSC would have a longer lifecycle than a database and can be reused for multiple databases (like for example is the case with Elastic Cloud GCP PSC: https://www.elastic.co/guide/en/cloud/current/ec-traffic-filtering-psc.html which publish a list of per region target attachment URIs so you can provision the GCP PSC ahead of time) so that's why I asked hoping that there is an option.

Unfortunately, the way Astra works right now is that the GCP PSC target is the service name, which is dependent upon the resources Astra creates as part of provisioning a Private Link. There would have to be a change in how Astra works for this to be possible. If that happens, we should be able to accommodate it within the provider.

Thanks again for the feature request. Closing this issue for now.

**Comment by oscar-b** [comment]
@emerkle826 @muresan I've ran into the same issue, I want to setup re-usable PSC in my Shared VPC, for a cluster with multiple deployments to connect to multiple different AstraDBs through one PSC. According to answers from our contact at Astra, this is possible; the service name will be the same per cloud, region and organisation.

So according to that, it should be possible to get the needed endpoint (with just cloud and region as input), is this something that could be added as a Terraform data resource?
