### ISSUE TITLE
TERRA-42 ⁃ Enable "Restrict Public Access" through Terraform

### ISSUE THREAD

**Issue by edmeister** [datastax/terraform-provider-astra#48]
Hi, we recently signed up for Astra Serverless and are trying to manage as much as possible with Terraform. We are wondering if it's already possible to enable the "Restrict Public Access" setting. Thanks in advance!

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-42) by [Unito](https://www.unito.io)
┆friendlyId: TERRA-42
┆priority: Major

**Comment by emerkle826** [comment]
It's not currently possible and would need to be added to the plugin.

**Comment by edmeister** [comment]
Thanks for your reply. 

It seems like this action is not exposed through the API, so it might be tough to implement.

**Comment by emerkle826** [comment]
I think we could do it through this endpoint:
https://docs.datastax.com/en/astra/docs/_attachments/devopsv2.html#operation/UpdateAccessListForDatabase
It seems to be the `configurations` section that needs to be enabled and I think this would do it.

**Comment by edmeister** [comment]
Do you take pull requests? I can probably have a look this weekend and blow some dust off my Golang skills.

**Comment by jdonenine** [comment]
> Do you take pull requests? I can probably have a look this weekend and blow some dust off my Golang skills.

Hey @edmeister we definitely do, so if you'd be interested in working on it that would be awesome.  Before we could accept the contribution we'd just need you to sign our CLA, other than that we'd just work through reviewing the changes together here as usual.

I know @emerkle826 has taken an initial look at things here and we talked a bit yesterday about how to best handle this in different creation/update scenarios.  From the conversation we had I'd say it's mildly complicated by the fact that in the DevOps API the access list resources and the configuration (where the setting you're looking for) are held within the same endpoint.  So it will take a little bit of thinking about how to use the endpoints properly and may take multiple requests for a single terraform resource.

For example, in the link that @emerkle826 mentioned in a previous comment that's a PATCH that can alter the flag, we're assuming at the moment that that can be used to only flip the flag without mucking with the list items themselves, it should, but stuff like that will need to be confirmed.

You'll also see that the POST form of the endpoint doesn't allow you to make that setting, but rather only to create access list items.  PUT can do both, but would in theory require the full payload every time something is edited.

**Comment by edmeister** [comment]
Hi @jdonenine, thanks for your reply. Happy to help out here, so I'll try to find your CLA.

From what I checked last weekend:
- Initial create should unfortunately require two calls (POST for the list + PATCH for the `accessListEnabled` configuration)
- Updates can use the PUT (why would you prefer not to touch the access list if only `accessListEnabled` has changed?)

**Comment by jdonenine** [comment]
> Hi @jdonenine, thanks for your reply. Happy to help out here, so I'll try to find your CLA.

I suppose I could have actually included the link 😄 https://cla.datastax.com/

> From what I checked last weekend:
> 
>     * Initial create should unfortunately require two calls (POST for the list + PATCH for the `accessListEnabled` configuration)

That jives with what @emerkle826 and I talked through yesterday.

>     * Updates can use the PUT (why would you prefer not to touch the access list if only `accessListEnabled` has changed?)

My concern would be related to what happens if a change is made to the set of access lists outside the scope of Terraform.  If terraform then reapplies it's entire state of access lists each time for the sake of updating the configuration flag, are we stomping on those changes.  My concern there might not be terribly well founded though, that same concern probably exists for any resource here, since they could all be manipulated outside of terraform as well.  

What do you think here @emerkle826?

My only thought might be, if the *only* thing being changed via terraform is the flag, use the patch and *only* modify the flag -- leave all of the access list items as they were.  I'm not sure how much that idea complicates things in the provider code though.

**Comment by emerkle826** [comment]
> From what I checked last weekend:
> 
>     * Initial create should unfortunately require two calls (POST for the list + PATCH for the `accessListEnabled` configuration)

This should work fine from a Terraform perspective, at least for Adds and Deletes. The code in the plugin will bundle the 2 Astra operations, so it will appear to be an atomic operation on the Terraform side.

>     * Updates can use the PUT (why would you prefer not to touch the access list if only `accessListEnabled` has changed?)

This gets tricky, and is about where I stopped digging. The implementation will dictate if Terraform decides to perform the update by deleting and re-adding the resource, or just updating the existing resource.

I haven't dug into the Astra API enough to figure out how `PUT` actually works. `PATCH` only updates the bits that are provided in the request to Astra, and leaves the rest alone. `PUT` may require you to provide the entire access-list contents. So if you use `PUT` and only provide the `accessListEnabled` flag, it likely wipes out any addresses you may have previously configured. But that may be exactly how this should work in Terraform, since the update would be from the diff tracked by Terraform. An example would be where you define addresses and then comment one out and do a `terraform apply`. It could just issue a `PUT` to Astra with the same addresses terraform already has, and the commented one simply removed from the list. Again, it's in the implementation details.

> My concern would be related to what happens if a change is made to the set of access lists outside the scope of Terraform

I think we have this problem in general with any resource, as you said.

**Comment by emerkle826** [comment]
>     * Updates can use the PUT (why would you prefer not to touch the access list if only `accessListEnabled` has changed?)

Upon further digging, "updates" aren't something this plugin seems to support for any resources currently. It's either ADD, DELETE or READ, where the only "updating" happens by deleting a resource and then re-adding it. So for now, this may be as simple as changing the ADD function to issue the PATCH to update the `accessListEnabled`

**Comment by edmeister** [comment]
> > My concern would be related to what happens if a change is made to the set of access lists outside the scope of Terraform
> 
> I think we have this problem in general with any resource, as you said.

In most of the providers I'm frequently using (if not all), I notice Terraform would show a warning during the `plan` (something like "Resources have been changed outside of Terraform"), if there is a mismatch between the tfstate and reality. The `apply` would override the actual configuration based on what is configured in Terraform. If people decide to use Terraform to manage their Astra instance, Terraform should definitely be the single source of truth. Not some hybrid thing.

When it comes down to "any addresses you may have previously configured" (or any resources in general), those can easily be brought under Terraform-control using `terraform import`.
