### ISSUE TITLE
TERRA-59 ⁃ astra_database module should expose the datacenter

### ISSUE THREAD

**Issue by sflandergan** [datastax/terraform-provider-astra#99]
Hi,

when provisioning an Astra DB instance the `astra_database` module won't give access to the datacenter.
The datacenter id is needed for `astra_private_link` and `astra_private_link_endpoint` though.
The examples in the `astra_private_link` documentation are wrong since they miss the suffix of the datacenter - for me `-1`.

### Terraform Version

```
Terraform v1.1.8
on linux_amd64
+ provider registry.terraform.io/datastax/astra v2.0.4
+ provider registry.terraform.io/hashicorp/azurerm v3.4.0
```

### Affected Resource(s)
Please list the resources as a list, for example:

* astra_database
* astra_private_link
* astra_private_link_endpoint

### Expected Behavior
The `astra_database` module should give access to the datacenters.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-59) by [Unito](https://www.unito.io)
┆friendlyId: TERRA-59
┆priority: Major

**Comment by emerkle826** [comment]
This is not a trivial request as a Database can have multiple datacenters (when deployed to multiple regions). Currently, the provider supports multi-region, but datacenter ID is not associated with the region in the module. I'll try to come up with something that is doable soon.

**Comment by emerkle826** [comment]
@sflandergan I have a solution, but I don't know how easy it will be to use. It creates a `datacenetrs` list on the database object, because you could have multiple datacenters. The TF state would look like this:
```yaml
resource "astra_database" "terra59" {
    additional_keyspaces = []
    cloud_provider       = "GCP"

    ...

    datacenters          = [
        {
            cloud_provider = "GCP"
            id             = "26592405-0856-41cd-90ec-c25d039f4c13-1"
            region         = "us-east4"
        },
    ]

    ...

    id                   = "26592405-0856-41cd-90ec-c25d039f4c13"

    ...
    regions              = [
        "us-east4",
    ]

    ...
```
However, when trying to reference the datacenter ID in a private link or private link endpoint resource, you'd have to reference it like this:
```yaml
resource "astra_database" "terra59" {
  name           = "terra59"
  keyspace       = "terra59"
  cloud_provider = "gcp"
  regions        = ["us-east4"]
}

resource "astra_private_link" "example" {
  allowed_principals = ["some-principal"]
  database_id = astra_database.terra59.id
  datacenter_id = astra_database.terra59.datacenters.0.id
}
```
This is because my implementation in [this PR](https://github.com/datastax/terraform-provider-astra/pull/110) represents the datacenter configuration as a list of objects. Apparently nested maps is a bit difficult to support in the Terrafrom data definitions. So if I go with this, you would have to know the index of the datacenter in the list to be able to reference it.

To be honest, this isn't much of an improvement over guessing the DC id from the database name and appending "-1". It is a slight improvement in that, as long as you know you'll only have 1 DC, then you know the index is `0`. But that improvement is quickly lost the minute you deploy to multiple regions (and have a DC for each). In that scenario, you will have to loop through the datacenters in the state and compare the cloud provider and region for the database you are trying to get the DC id of. That's a lot of tricky logic in a Terrafrom resource definition.

I'll hold off on merging that PR, and keep trying different approaches for now.

**Comment by emerkle826** [comment]
I have another implementation that maybe works better. With it, you could reference the datacenter id like this:
```yaml
resource "astra_database" "terra59" {
  name           = "terra59"
  keyspace       = "terra59"
  cloud_provider = "gcp"
  regions        = ["us-east4"]
}

resource "astra_private_link" "example" {
  allowed_principals = ["some-principal"]
  database_id = astra_database.terra59.id
  datacenter_id = astra_database.terra59.datacenters["${astra_database.terra59.cloud_provider}.${astra_database.terra59.regions[0]}"]
}
```
where you would only have to make sure you use the right regions index.

The state file would look like this instead:
```yaml
resource "astra_database" "terra59" {
    additional_keyspaces = []
    cloud_provider       = "GCP"

    ...

    datacenters          = {
        "GCP.us-east4" = "26592405-0856-41cd-90ec-c25d039f4c13-1"
    }


    ...

    id                   = "26592405-0856-41cd-90ec-c25d039f4c13"

    ...
    regions              = [
        "us-east4",
    ]

    ...
```

**Comment by sflandergan** [comment]
Hi @emerkle826 ,

the last proposed solution looks very promising :+1: 
I think that way people with a very simple setup can easily refer to the datacenter the way you mentionend.
More complex, multi region setups should be covered too.
